Ontotext-AD/graphdb-helm

- Chart.yaml
- templates/gateway/ingress.yaml
- templates/graphdb-master.yaml
- values.yaml
> Minor bugfixes

- files/scripts/graphdb.sh
- templates/graphdb-node.yaml
Fixed users.js and settings.js provisioning when security is on
Fixed cluster creation when security is on
> Fixed cluster creation script to use authorization when security is on

- Chart.yaml
- files/scripts/graphdb.sh
- templates/jobs/provision-repositories-job.yaml
- values.yaml
… resourcesAdded repositories provisioning option and updated proxy's probes and resources
> Added repositories provisioning option

- CHANGELOG.md
- Chart.yaml
- templates/_helpers.yaml
Made an image registry to have priority over global registry
Updated release version
> Fix overriding a single image registry to take priority over global registry

- .github/workflows/ci.yml
- .gitignore
- README.md
- trivy.yaml
Changes:
- Added CI workflow for PRs and the main branch
- Added build status badge in the readme
- Added trivy configuration
> GDB-9036: Added CI workflow

- files/scripts/update-cluster.sh
- templates/jobs/patch-cluster-job.yaml
Always getting timeouts here.
Would be great if we could merge this
> [graphdb]: use clusterCreationTimeout also in patchCluster

- Chart.yaml
Release the changes introduced with [GDB-9509](https://ontotext.atlassian.net/browse/GDB-9509)
[GDB-9509]: https://ontotext.atlassian.net/browse/GDB-9509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release GraphDB Helm 10.6.0-R2

- .github/workflows/ci-docs.yml
- README.md
- README.md.gotmpl
- values.yaml
- Added readme Go template used as a base for generating the readme with helm-docs
- Added new workflow that invokes helm-docs and pushes changes back to the PR
> GDB-9455: Added automatic readme generation with helm-docs

- Chart.yaml
- LICENSE
- Added ArtifactHub specific annotations in Chart.yaml
- Added Apache 2.0 license
> GDB-9029: Prepare for ArtifactHub

- CHANGELOG.md
- Chart.yaml
- README.md
- Updated appVersion to 10.7.3
- Updated chart's version to 11.1.3
> GDB-10729: Updated to GraphDB 10.7.3

- CHANGELOG.md
- Chart.yaml
- README.md
- templates/graphdb/statefulset.yaml
- templates/proxy/statefulset.yaml
Fixed `extraVolumeClaimTemplates` not being rendered properly by replacing  `if` statement with `with` in the graphdb and proxy StatefulSet templates.
> Fixed bug related to extraVolumeClaimTemplates rendering.

- examples/configuring/README.md
- examples/configuring/resources.yaml
This MR add examples about configuring GraphDB using Kubernetes ConfigMaps and Secrets. The document includes:
- Methods to manage configuration options securely and efficiently.
- Examples of setting properties, secret properties, and additional configurations.
- Instructions on setting Java arguments and environment variables for GraphDB.
- Best practices to ensure secure setup.
These updates aim to improve the clarity and security of the GraphDB configuration process.
Issue: [GDB-10778](https://ontotext.atlassian.net/browse/GDB-10778)
[GDB-10778]: https://ontotext.atlassian.net/browse/GDB-10778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GDB-10778 Added GraphDB configuration examples

- .editorconfig
- .gitattributes
- .gitignore
- Added global rules for utf-8, final new lines and so on
- Added .gitattributes to enforce unix line endings
- Ignored packaged Helm charts in git
> Added editorconfig to enforce some code styling rules

- files/config/users.js
- templates/_helpers.tpl
- values.yaml
Improve UX when configuring the Security Provisioner.
> GDB-10752 Fix Security Provisioner Password Hash

- examples/aws/backup/README.md
- examples/azure/backup/README.md
- templates/jobs/cronjob-backup.yaml
Fix:
- `secretRef` is element of a list structure (backup examples)
- The container name of the backup cronjob was not correct
> GDB-10778 Fix backup examples

- CHANGELOG.md
- Chart.yaml
- README.md
Updated GraphDB to 10.8.1
Bumped chart version to 11.3.1
> Release GraphDB 10.8.1

- CHANGELOG.md
- Chart.yaml
- README.md
- Updated the Helm chart to use GraphDB version 10.8.4
- Updated the Helm chart to version 11.3.5
> GDB-11527: Update to GraphDB 10.8.4

- CHANGELOG.md
- examples/gcp/backup/README.md
- examples/gcp/service-account/README.md
- examples/gcp/service-account/values.yaml
Created examples for configuring GCP Service Account and backups to Cloud Storage.
> Gdb 10819 add example for configuring service account and cloud backups for gcp

- CHANGELOG.md
- Chart.yaml
- README.md
- Updated the Helm chart to use GraphDB version 10.8.6
- Updated the Helm chart to version 11.4.2
> GDB-12010: Update to GraphDB 10.8.6

- CHANGELOG.md
- Chart.yaml
- README.md
- Updated the Helm chart to use GraphDB version 11.1.1
- Updated the Helm chart to version 12.1.1
> GDB-13043: Updated to GraphDB 11.1.1
