README.md
templates/graphdb-worker.yaml
templates/persistence/graphdb-preload-data-pv.yaml
templates/persistence/graphdb-preload-data-pvc.yaml
values.yaml

Closes [GDB-5620](https://ontotext.atlassian.net/browse/GDB-5620) As a DevOps I want to be able to launch GraphDB’s storage tool/preload tool/loadrdf tool through Helm, before launching GraphDB

GDB-5620 Graphdb helm tools

---

README.md

The chart has proven multiple times, so I dare say it's time to remove the warning.

Removed experimental warning

---

templates/graphdb-master.yaml

This should fix a bug when using volumeClaimTemplate. 
We were getting that error:
> Create Pod graphdb-master-1-0 in StatefulSet graphdb-master-1 failed error: Pod "graphdb-master-1-0" is invalid: spec.initContainers[3].volumeMounts[0].name: Not found: "graphdb-master-storage"

[bugfix]: fix restore-standalone volumeMount error

---

templates/graphdb-cluster-proxy.yaml
values.yaml

Current behaviour to to set the service type for graphdb-cluster-proxy to LoadBalancer. In AWS EKS with ALB installed this defaults to the public internet. Currently there is no way to safely deploy this helm chart in AWS EKS with ALB.
Change:
* Default values preserves current behaviour
* Possible to set the type to ClusterIP in the values override for secure deployment in AWS.

Make the service type of graphdb-cluster-proxy optional

---

.gitignore
templates/graphdb-master.yaml
templates/graphdb-worker.yaml
values.yaml

Updated both masters and workers to render additional configurations:
- Added `extraEnvFrom` applicable for all replicas
- Added `extraVolumes` and `extraVolumeMounts` applicable for all replicas
The new options will allow the provision of custom JARs in GraphDB.
Added gitignore

OTKG-110: Added the ability to further customize the deployments

---

templates/graphdb-master.yaml
templates/graphdb-worker.yaml

Updated the templates to use the global context (`$`) when rendering extra volumes, mounts and envFrom.

OTKG-110: Fixed the template rendering for extra configurations

---

CHANGELOG.md
Chart.yaml
templates/configuration/graphdb-cluster-proxy-configmap.yaml

Changed protocol that the cluster proxy adds the nodes to always be http
Prepared chart for 10.1.5-R2 release

Fixed an issue with cluster proxy connecting to nodes when protocol is set to https

---

.gitignore
CHANGELOG.md
README.md
files/scripts/graphdb.sh
files/scripts/update-cluster.sh
templates/configuration/graphdb-cluster-config-configmap.yaml
templates/graphdb-cluster-proxy.yaml
templates/graphdb-node.yaml
templates/graphdb-provision-user-secret.yaml
templates/jobs/patch-cluster-job.yaml
templates/jobs/post-start-job.yaml
templates/jobs/provision-repositories-job.yaml
templates/jobs/scale-down-cluster-job.yaml
templates/jobs/scale-up-cluster-job.yaml
values.yaml

Added .gitignore
Added security context to pods and containers of the statefulsets
Added jobSecurityContext and jobContainerSecurityContext
Added extraEnv, extraVolumes and extraVolumeMounts to the statefulsets
Added Ontotext's Helm repository to README
Added an optional PV/PVC for the proxy to properly preserve logs when someone has readonly by default 
Changed graphdb.properties and logback.xml provisioning to overwrite any previously set such files
Fixed graphdb-cluster-config-configmap.yaml to not render when there isn't a cluster
Moved the default values of nodeSelector, affinity, tolerations and topologySpreadConstraints from the statefulsets to the values.yaml
Moved the provision user credentials to its own secret so the job's don't render an authentication token
Updated default …

Various improvements to the chart gdb 7987 7985 7984 7978 and more

---

.helmignore
CHANGELOG.md
examples/openshift-local/README.md
examples/openshift-local/values.yaml
templates/jobs/patch-cluster-job.yaml
templates/jobs/post-start-job.yaml
templates/jobs/provision-repositories-job.yaml
templates/jobs/scale-down-cluster-job.yaml
templates/jobs/scale-up-cluster-job.yaml
values.yaml

**Tuned the cluster proxy probes**
- Switched the startup probe to use `/proxy/ready`
- Increased the startup failureThreshold
- Lowered the startup period to allow faster readiness
- Lowered the readiness initialDelaySeconds to allow faster registration
All of these changes should allow the proxy to become available sooner.
**Updated the Jobs**
- Updated the cluster and repositories jobs with simpler arguments removing
  the need to copy scripts and to make them executable
- Added ephemeral volumes in the cluster and repositories jobs to avoid issues
  with readonly file systems
These changes allow GraphDB to be deployed on more strict Kubernetes clusters.
**Added OpenShift example deployment**
Introduced new directory structure examples/ for various deployment scenarios.
Added …

DEVSUP-28: GraphDB on OpenShift

---

CHANGELOG.md
templates/NOTES.txt
templates/_helpers.yaml
templates/configuration/graphdb-cluster-proxy-configmap.yaml
templates/configuration/graphdb-node-configmap.yaml
templates/gateway/ingress.yaml
templates/graphdb-cluster-proxy.yaml
templates/graphdb-node.yaml
templates/jobs/patch-cluster-job.yaml
templates/jobs/post-start-job.yaml
templates/jobs/provision-repositories-job.yaml
templates/jobs/scale-down-cluster-job.yaml
templates/jobs/scale-up-cluster-job.yaml
values.yaml

Changes:
- GDB-8218: Added extra environment variables: Added extraEnv configurations for both the GraphDB nodes and cluster proxies.
- GDB-8219: Configure revision history: Added `revisionHistoryLimit` configurations for nodes and cluster proxies.
- GDB-8217: Configure extra pod labels and annotations: Added configurations for adding extra `podLabels` and `podAnnotations` for
- both the nodes and cluster proxies.
- GDB-7985: Skip rendering empty configurations
- GDB-8219: Configure termination grace period: Added configurations for `terminationGracePeriodSeconds` to both the nodes and cluster proxies.
- GDB-7985: Removed unused helper template
- GDB-7993: Updated helper templates naming: Added `graphdb` prefix in the helper templates function naming

DEVSUP-40: Helm Improvements

---

CHANGELOG.md
files/config/users.js

Currently the provisioner was hard coded and not extracted from the values.yaml and if we changed it there we end up with an error.

GDB-8277 fix users.js config file

---

CHANGELOG.md
Chart.yaml
templates/configuration/graphdb-cluster-config-configmap.yaml
templates/configuration/graphdb-cluster-proxy-configmap.yaml
templates/configuration/graphdb-logback-configmap.yaml
templates/configuration/graphdb-node-configmap.yaml
templates/configuration/graphdb-properties-configmap.yaml
templates/configuration/graphdb-settings-configmap.yaml
templates/configuration/graphdb-users-configmap.yaml
templates/gateway/ingress.yaml
templates/graphdb-cluster-proxy.yaml
templates/graphdb-node.yaml
templates/graphdb-provision-user-secret.yaml
templates/graphdb-utils-configmap.yaml
templates/jobs/patch-cluster-job.yaml
templates/jobs/post-start-job.yaml
templates/jobs/provision-repositories-job.yaml
templates/jobs/scale-down-cluster-job.yaml
templates/jobs/scale-up-cluster-job.yaml
values.yaml

Changes:
- GDB-8328: Removed versions field: There isn't any practical need for having apiVersion as configurations.
- GDB-7983: Enriched Chart.yaml info: Added additional meta information about the chart.
- GDB-8216: Directly mounted the license: No need to provision it via initContainer when it can just be mounted.
- GDB-8308: Added configurations for graphdb-node command and args: The configurations can be useful during troubleshooting.
- Removed unused persistence configurations
- Removed unused graphdb-node-storage volume mount
- Removed unused deployment.storage config
- GDB-7989: Added Pod Disruption Budget for the GraphDB nodes
- GDB-8038: Tuned resource requests and limits
- Removed CPU limits which is an anti-pattern
- Lowered the default CPU requests

GDB-8287: Helm improvements for extendability

---

CHANGELOG.md
Chart.yaml
templates/graphdb-cluster-proxy.yaml
templates/graphdb-node.yaml
values.yaml

The configurations cover:
- GraphDB node service `graphdb.node.service.annotations`
- GraphDB cluster proxy service `graphdb.clusterProxy.service.annotations`
- GraphDB cluster proxy headless service `graphdb.clusterProxy.headlessService.annotations`

Added configurations for extra service annotations

---

templates/graphdb-node.yaml

... so we don't fail if no volumeClaimTemplateSpec defined
Otherwise, if `volumeClaimTemplateSpec` is not defined, we will produce wrong yaml.

fix: include mountPath within proper section

---

README.md

The original URL now leads to a 404 page. 
I've modified the URL so it points to the correct address.

Fixed "How to configure Hosts file" broken link.

---

CHANGELOG.md
templates/graphdb-cluster-proxy.yaml
templates/graphdb-node.yaml
values.yaml

Added `graphdb.node.extraInitContainers` and `graphdb.clusterProxy.extraInitContainers` that allows for the insertion of custom init containers to both GraphDB and its proxy.

GDB-9190: Extra init containers

---

CHANGELOG.md
files/config/cluster-config.json
templates/configuration/graphdb-cluster-config-configmap.yaml
templates/jobs/patch-cluster-job.yaml
templates/jobs/post-start-job.yaml
values.yaml

- Added `graphdb.clusterConfig.transactionLogMaximumSizeGB` configuration for the cluster creation JSON configuration
- Added `graphdb.clusterConfig.existingClusterConfig` for providing a custom cluster creation JSON configuration
- Fixed URLs in the [README.md](README.md) that refer to the official GraphDB documentation
- Fixed the cluster creation JSON configuration to use `messageSizeKB` instead of `messageSize`, see `graphdb.clusterConfig.messageSize`

GDB-9509: Updated the cluster creation JSON configuration

---

.helmignore
README.md
README.md.gotmpl

- Added examples on how to install GraphDB Helm chart from Ontotext Helm repository
- Added examples on how to verify the Helm chart provenance and integrity with our public GnuPG key
- Added additional .helmignore rules

GDB-9222: Added repo install and provenance information

---

templates/gateway/ingress.yaml

This PR moves the ingress-class from the annotations to the spec section. Using the annotations was deprecated in k8s 1.18.
https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/

Change from ingress class annotation to ingressClassName in spec

---

templates/graphdb-node.yaml

The test commands in the script require bash to be executed. However with `sh` they fail.
This is broken since 1.6.x helm charts. My guess, the busybox image changed the default shell.

fix provisioning init container

---

CHANGELOG.md
Chart.yaml
README.md
files/scripts/graphdb.sh
files/scripts/update-cluster.sh
templates/graphdb/statefulset.yaml
templates/jobs/job-create-cluster.yaml
templates/jobs/job-patch-cluster.yaml
templates/jobs/job-provision-repositories.yaml
templates/jobs/job-scale-down-cluster.yaml
templates/jobs/job-scale-up-cluster.yaml
templates/proxy/statefulset.yaml

Changes:
- Updated all cluster jobs to explicitly use `/tmp` as a working directory to avoid permission errors due to the default security context's `readOnlyRootFilesystem` when the container has a starting folder different from `/tmp`.
- Updated all utility scripts to use temporary files under `/tmp` for the same reason.
- Prepared for version 11.0.1

GDB-10462: Updated cluster jobs to always use the temp folder

---

examples/aws/ingress/README.md
examples/aws/ingress/values.yaml
examples/aws/ingress/values_https.yaml
examples/aws/lb-example/README.md
examples/aws/lb-example/values.yaml
examples/aws/lb-example/values_https.yaml
examples/aws/service-account/README.md
examples/aws/service-account/values.yaml

- Added examples for deploy the chart with:
- Service: Load Balancer type
- Ingress with ALB
- Service Account

Added examples for NLB, ALB ingress and service account

---

examples/aws/ingress/README.md
examples/aws/ingress/values.yaml
examples/aws/ingress/values_https.yaml
examples/aws/lb-example/README.md
examples/aws/lb-example/values.yaml
examples/aws/lb-example/values_https.yaml
examples/aws/service-account/README.md
examples/aws/service-account/values.yaml
examples/azure/ingress/README.md
examples/azure/ingress/values.yaml
examples/azure/ingress/values_https.yaml
examples/azure/lb-example/README.md
examples/azure/lb-example/values.yaml
examples/azure/service-account/README.md
examples/azure/service-account/values.yaml

- Added support for using Service Account with Azure Workload Identity
- Added support for using Application Gateway Ingress 
- Added support for using Service type LoadBalancer with Application Gateway Ingress in order to provide SSL.

[GDB-10412] Add examples for deploying GraphDB in Azure

---

CHANGELOG.md
templates/graphdb/statefulset.yaml
templates/proxy/statefulset.yaml

Updated the GraphDB containers to explicitly use `/tmp` as a working directory to avoid permission errors due to the  default security context's `readOnlyRootFilesystem` when the container has a starting folder different from `/tmp`.

GDB-10521: Set the containers workdir

---

examples/security/README.md
examples/security/graphdb-users.yaml

This MR adds examples for provisioning users in GraphDB with security enabled. It includes detailed steps for configuring the admin and provisioner accounts, adding additional users, and using a custom Secret resource for user management.

GDB-10780 Add GraphDB security configurations examples

---

examples/configuring/README.md
examples/configuring/resources.yaml

Fix the mistakes and unclear wording from PR #122 .

GDB-10778 Fix GraphDB configuration examples

---

examples/virtualization/README.md

The examples describe how to provide JDBC drives to GraphDB's classpath in two different ways, one of which is by copying them with `kubectl`.
Added a short description for a third option that includes an existing PV.

GDB-10532: Added configuration examples for GraphDB virtualization features

---

CHANGELOG.md
examples/plugins/README.md
templates/graphdb/configmap-properties.yaml

The examples describe how to provide plugin JARs to GraphDB's classpath in two different ways, one of which is by copying them with `kubectl`.
Added short description for a third option that includes an existing PV.
Configured `graphdb.extra.plugins` to load plugins from `/opt/graphdb/home/extra-plugins` by default.

GDB-10532: Added configuration examples for extra GraphDB plugins

---

examples/aws/backup/README.md
examples/azure/backup/README.md

Fix Helm throwing error (`found character that cannot start any token`) when `@midnight` is not quoted when used (mentioned in AWS and Azure backups examples).

GDB-10777 Fix backup examples

---

CHANGELOG.md
templates/jobs/configmap-utils.yaml
templates/jobs/job-scale-down-cluster.yaml
templates/jobs/secret-provision-user.yaml

Removed any pre-install, pre-upgrade, pre-rollback Helm hooks annotations to allow seamless ArgoCD deployments. 
Such hooks were used in:
- configmap-utils.yaml
- secret-provision-user.yaml
- job-scale-down-cluster.yaml

GDB-8948: Improved ArgoCD compatibility

---

templates/graphdb/configmap-properties.yaml

If there is no mounted license, GraphDB would error therefore we need to check for the presence of a configured license secret.

Added check when configuring the license path

---

CHANGELOG.md
Chart.yaml
README.md

- Increased the GraphDB version to 10.8.2
- Increased the Helm chart version to 11.3.2

GDB-11366: Release GraphDB 10.8.2

---

examples/grpc-security/README.md
examples/grpc-security/certWithoutChain.yaml
examples/grpc-security/jsse.yaml
examples/grpc-security/openssl.yaml

Created a description and values.yaml files that show all the ways to set up the GraphDB gRPC cluster communication SSL/TLS.

Added example for configuring cluster gRPC TLS/SSL

---

templates/graphdb/configmap-properties.yaml
templates/proxy/configmap-properties.yaml

Formatted TLS properties so instead of being multiline, each property in the configmap is displayed on a single line .

Fixed formatting in configmap-properties file

---

CHANGELOG.md
Chart.yaml
README.md
templates/graphdb/configmap-properties.yaml
templates/proxy/configmap-properties.yaml

The config maps for both GraphDB and the cluster proxy were rendering all values from `configuration.properties` in quotes which is problematic because some properties are expected as non-strings.
Removed `| quote` to allow non-string values such as booleans and numbers.
Prepared Helm release v11.3.3

GDB-11494: Avoid rendering GraphDB properties in quotes

---

CHANGELOG.md
Chart.yaml
README.md

- Updated the Helm chart to use GraphDB version 10.8.3
- Updated the Helm chart to version 11.3.4

GDB-11527: Update to GraphDB 10.8.3

---

CHANGELOG.md
Chart.yaml
examples/templated-extra-objects/README.md
examples/templated-extra-objects/values.yaml
templates/extra-objects.yaml
values.yaml

The chart can now render string templates added in `extraObjects` array in values of the chart. This change will allow users to also use helm templating functions inside the extra objects providing them more flexibility.
The render loop first test if the item in array is a string or not. If it's not a string, then it's processed via `toYaml` first.
An example values.yaml is also added to show how this feature will work

feat: add support to render string Helm templates in `extraObjects`

---

CHANGELOG.md
Chart.yaml

- Updated the Helm chart to use GraphDB version 10.8.8
- Updated the Helm chart to version 11.4.4

GDB-12470: Update to GraphDB 10.8.8

---

CHANGELOG.md
Chart.yaml
README.md

- Updated the Helm chart to use GraphDB version 10.8.9
- Updated the Helm chart to version 11.4.5

GDB-12470: Update to GraphDB 10.8.9
